# These are supported funding model platforms

patreon: kokoraka
open_collective: arjuna
ko_fi: kokoraka
liberapay: arjuna
issuehunt: gurisa/arjuna
otechie: arjuna
custom: ['https://idaman.id/arjuna']

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
